### ISSUE TITLE
Idris Typechecking Delay

### ISSUE THREAD

**Issue by Chinmaya-Kausik** [siddhartha-gadgil/LTS2019#101]
Typechecking for my latest version of the Cosets.idr file is taking a very long time (Anywhere between 12-45 minutes). Any suggestions?

It seems to be a problem in the file (occurs across various systems)

**Comment by anotherArka** [comment]
Divide the contents in different files.

**Comment by anotherArka** [comment]
That way first time compilation will take the same time but I think subsequent compilation will take less time, given you don't change the imported files.

**Comment by anotherArka** [comment]
Or just comment out the code you are not using.

**Comment by Chinmaya-Kausik** [comment]
> Divide the contents in different files.

I have already tried this. It doesn't really make a difference

**Comment by Chinmaya-Kausik** [comment]
> That way first time compilation will take the same time but I think subsequent compilation will take less time, given you don't change the imported files.

That does not seem to be the case

**Comment by Chinmaya-Kausik** [comment]
> Or just comment out the code you are not using.

I am using most of the code that causes an issue, due to heavy interdependence

**Comment by siddhartha-gadgil** [comment]
Has this been pulled to my master? There is no delay on my system.

**Comment by Chinmaya-Kausik** [comment]
> Has this been pulled to my master? There is no delay on my system.

It is now in the file Cosets.idr

**Comment by Chinmaya-Kausik** [comment]
> Typechecking for my latest version of the Group.idr file is taking a very long time (Anywhere between 12-45 minutes). Any suggestions?
> 
> It seems to be a problem in the file (occurs across various systems)

**Comment by Chinmaya-Kausik** [comment]
Any suggestions?

**Comment by siddhartha-gadgil** [comment]
Is this uploaded to GitHub in your report?

**Comment by Chinmaya-Kausik** [comment]
It has been pulled to your repository, as the file Cosets.idr. It does typecheck, only that idris takes 20-45 minutes to do this.

I'm not sure what you mean by "on my my report". I haven't yet submitted my markdown file, if that's what you mean. If you mean to say "on my version of the repository," then yes, it is there as well.

**Comment by siddhartha-gadgil** [comment]
Will look at it. I meant repo, i.e. repository. Autocompletion messed it up.

**Comment by siddhartha-gadgil** [comment]
Here are some results of my experimentation and some suggestions:
* Firstly, the code at present does not compile (but don't try to fix this, instead make other changes suggested below).
```idris
   |
28 | corepfinv h (+) pf1 g (*) pf2 sbgrp trav pftrav y = (sym ((fst (snd pftrav)) y t (p ** (sym (snd (snd  ((snd (snd pftrav)) (f y)) )))) )) where
   |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
When checking right hand side of corepfinv with expected type
        fst (snd (snd (snd pftrav) (fst pftrav y))) = y

Can't disambiguate name: Prelude.Basics.snd, Prelude.Pairs.DPair.snd

Cosets.idr:55:20-68:
   |
55 |   CorepFInverseY = CorepFInv h (-) pf1 g (*) pf2 sbgrp trav pftrav y
   |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
When checking right hand side of Cosets.MulTravHomPf, CorepFInverseY with expected type
        fst (snd (snd (snd pftrav) (fst pftrav y))) = y

No such variable CorepFInv

Holes: Cosets.MulTravHomPf, Cosets.corepfinv
```
* Even if there is no error as above, disambiguating `fst` and `snd` is a lot of work for _idris_, plus using just iterated pairs makes code harder to read and maintain.
* It is better to introduce a type for _transversals_ (by the way they are transversals, not traversals) with a single constructor, and then define a bunch of functions that take apart meaningful pieces. Here is an analogous definition for groups (which too you should probably use)
```idris
data GroupStructure :  (group: Type) ->  Type where 
MkGroup: (group: Type) -> ((*) : grp -> grp -> grp) -> Associative grp (*) -> ... -> GroupStructure(grp)
```
* For the `MkTraversal` constructor, use names for variables even if you do not use them, just for documentations.
* As @anotherArka suggested, have the definitions for the traversal type and its pieces in a separate file.

**Comment by siddhartha-gadgil** [comment]
I can't see if this is alive, so I am closing it. Please reopen if there is an issue still
