### ISSUE TITLE
some files seem to have been deleted

### ISSUE THREAD

**Issue by AR-MA210** [siddhartha-gadgil/LTS2019#202]
Various files that were in the folder Code recently seem to have been removed, such as VectPerm.idr, Ring.Properties.idr, All_is_Refl.idr, pigeonhole.idr, etc (this is not a comprehensive list). I am not sure of what might have happened, but how should we bring these files back?

**Comment by siddhartha-gadgil** [comment]
I made a mess with a commit this morning. I will try to restore stuff.

**Comment by siddhartha-gadgil** [comment]
For now, I have restored state to before the mess. I will try to merge in the changes made in the last 24 hours cleanly.

**Comment by siddhartha-gadgil** [comment]
I have restored shafil's changes, but could not restore yours (i.e. of @AR-MA210 ) as I cannot figure out whether, for example, `data NotZero: ` is in `ZZUtils` or in  `Rationals`. Please have a clean version of the code basing on the upstream branch.

**Comment by AR-MA210** [comment]
I had made a mistake with the imports as well as the location of NotZero. It's fixed now and I apologize for the errors.

**Comment by siddhartha-gadgil** [comment]
@AR-MA210 @shafilmaheenn @anotherArka please check that none of your work has been accidentally deleted. If all is fine we can close this issue.

**Comment by shafilmaheenn** [comment]
My work is intact.

**Comment by AR-MA210** [comment]
My contributions are intact too.
