### ISSUE TITLE
Different folders for each project.

### ISSUE THREAD

**Issue by anotherArka** [siddhartha-gadgil/LTS2019#30]
Can we have different folders for each project? Otherwise it might get a bit messy as more and more and files are getting added.

**Comment by siddhartha-gadgil** [comment]
As far as I can see, Idris handles files across different folders badly. It may be best to work in a single folder, but try to have larger files rather than more of them.

**Comment by siddhartha-gadgil** [comment]
As discussed, we will use naming conventions instead
