### ISSUE TITLE
Tools file

### ISSUE THREAD

**Issue by adithyaupadhya** [siddhartha-gadgil/LTS2019#64]
Should we perhaps put a collection of basic proofs that might be useful in lots of places, (for example a proof that S m = Sn => m = n, functions like sillyCasts, or more like these) in a separate file (with module name Tools or some such thing)? It reduces clutter in files that aim at solving projects and makes code easier to read. In general, splitting code across files would make it seem less like a wall of text.

**Comment by SS-C4** [comment]
Also, can we all please include
 _%access public export_
in all files, whenever we author them?

**Comment by siddhartha-gadgil** [comment]
Do spilt into files, but try to keep descriptive names for both files and functions, so tools should be fit further, say `NatUtils` with utility functions for natural numbers. And rename functions such as `sillyCast`
